[package]
name = "luwen"
version = "0.3.3"
edition = "2021"
license = "Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
luwen-core = {path = "crates/luwen-core"}
luwen-if = {path = "crates/luwen-if"}
luwen-ref = {path = "crates/luwen-ref"}
kmdif = {path = "crates/kmdif"}

serde = {"version" = "1.0.164", features = ["derive"]}
serde_yaml = "0.9.22"
bincode = "1.3.3"
rand = "0.8.5"
nom = "7.1.3"
clap = {version = "4.4.14", features = ["derive"]}

[workspace]
members = [
    "crates/*"
]

